-primer_django/urls.py
from django.contrib import admin
from django.urls import path
from primer_django.views import inicio, segunda_vista, fecha_actual, saludar, crear_persona
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio),
    path('segunda-vista/', segunda_vista),
    path('fecha-actual/', fecha_actual),
    path('saludar/<str:nombre>/<str:apellido>/', saludar ),
    path('crear-persona/<str:nombre>/<int:edad>/', crear_persona )
]
   

inicio/urls.py
from django.contrib import admin
from django.urls import path
from inicio.views import inicio, segunda_vista, fecha_actual, saludar, crear_persona, crear_gato

app_name= 'inicio'

urlpatterns = [
    path('', inicio, name= 'inicio'),
    path('admin/', admin.site.urls),
    path('segunda-vista/', segunda_vista, name= 'prueba'),
    path('fecha-actual/', fecha_actual),
    path('saludar/<str:nombre>/<str:apellido>/', saludar ),
    # path('crear-persona/<str:nombre>/<int:edad>/', crear_persona),
    path('crear-persona/', crear_persona, name= 'crear-persona'),
    # path('crear-Pajaro/', crear_pajaro, name= 'crear-pajaro'),
    path('crear-Gato/', crear_gato , name= 'crear-gato'),
]

primer_django/urls.py
from django.contrib import admin
from django.urls import path, include
from inicio.views import inicio, segunda_vista, fecha_actual, saludar, crear_persona
urlpatterns = [
    path('', include('inicio.urls')),
    path('admin/', admin.site.urls),
]
   

-primer_django/models.py
from django.db import models

class Perro(models.Model):
    nombre = models.CharField(max_length=24)
    edad = models.models.IntegerField()
    
class Gato(models.Model):
    nombre = models.CharField(max_length=24)
    edad = models.IntegerField()

class Pajaro(models.Model):
    nombre = models.CharField(max_length=24)
    edad = models.IntegerField()

inicio/models.py
from django.db import models

# Create your models here.

class Persona(models.Model):
    nombre = models.CharField(max_length=20)
    edad = models.IntegerField()
    
    
class Gato(models.Model):
    nombre = models.CharField(max_length=24)
    edad = models.IntegerField()

# class Pajaro(models.Model):
#     nombre = models.CharField(max_length=24)
#     edad = models.IntegerField()

primer_django/models.py
from django.db import models

class Perro(models.Model):
    nombre = models.CharField(max_length=24)
    edad = models.models.IntegerField()
    
class Gato(models.Model):
    nombre = models.CharField(max_length=24)
    edad = models.IntegerField()

#class Pajaro(models.Model):
#    nombre = models.CharField(max_length=24)
#    edad = models.IntegerField()

-primer_django/views.py
from django.http import HttpResponse
from datetime import datetime
from django.template import Template, Context, loader
from inicio.models import Persona
#v1
#def inicio(request):
#    return HttpResponse ('Inicio')

#v2

#def inicio(request):
#    archivo = open(r'C:\Users\matia\Desktop\python\templates\inicio.html', 'r')
    
    #emplate = Template(archivo.read())
    
#    archivo.close()
    
    #diccionario = {
     #   'mensaje' : 'mensaje de inicio'
    #}
    
   # contexto = Context (diccionario)
    
   # renderizar_template = template.render(contexto)
    
   # return HttpResponse (renderizar_template)

#v3
def inicio(request):

    template = loader.get_template('inicio.html')
    
 
    diccionario = {
        'mensaje' : 'mensaje de inicio'
    }
    
    #contexto = Context (diccionario)
    
    renderizar_template = template.render(diccionario)
    
    return HttpResponse (renderizar_template)


    

def segunda_vista(request):
    return HttpResponse ('<h2>Segunda vista <h2>')

def fecha_actual(request):
    fecha= datetime.now()
    return HttpResponse (f'<h1>Fecha actual:{fecha}<h1>')

def saludar(request, nombre, apellido):
    return HttpResponse (f'hola! {nombre.title()} {apellido.title()}')


def crear_persona(request, nombre, edad):
    template = loader.get_template('crear-persona.html')
    persona = Persona(nombre=nombre, edad=edad)
    persona.save()    
    
    diccionario = {
        'persona': Persona
    }

    renderizar_template = template.render(diccionario)
    return HttpResponse (renderizar_template)

inicio/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponse
from datetime import datetime
from django.template import Template, Context, loader
from inicio.models import Persona, Gato, Pajaro
from django.shortcuts import render
from inicio.form import CrearPersonaFormulario, CrearGatoFormulario 

def inicio(request):

    # template = loader.get_template('inicio.html')
    
 
    diccionario = {
        'mensaje' : 'mensaje de inicio'
    }
    
    #contexto = Context (diccionario)
    
    # renderizar_template = template.render(diccionario)
    
    # return HttpResponse (renderizar_template)
    return render(request,'inicio.html')



    

def segunda_vista(request):
    return HttpResponse ('<h2>Segunda vista <h2>')

def fecha_actual(request):
    fecha= datetime.now()
    return HttpResponse (f'<h1>Fecha actual:{fecha}<h1>')

def saludar(request, nombre, apellido):
    return HttpResponse (f'hola! {nombre.title()} {apellido.title()}')





def crear_persona(request):    
    diccionario= {}
    
    if request.method == "POST":
        formulario= CrearPersonaFormulario(request.POST)
        if formulario.is_valid():
            info= formulario.cleaned_data
            persona = Persona(nombre=info ['nombre'] , edad= info ['edad'] )
            persona.save()    
    
            diccionario ['persona']= persona
            
    formulario= CrearPersonaFormulario()
    
    diccionario['formulario'] = formulario
        
    return render(request,'crear-persona.html', diccionario)


def crear_gato(request):    
    if formulariogato == CrearGatoFormulario(request.POST):
        if formulariogato.is_valid():
            data= formulariogato.cleaned_data
            gato= Gato(nombre=data['nombre'], edad = data ['edad'])
            Gato.save()
    formulariogato= CrearGatoFormulario()
    return render (request, 'crear-gato.html', {'formulariogato': formulariogato})

templates/base.html
<!DOCTYPE html>
<html lang="en">
    {% load static %}
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% block  title_head %}
        <title>inicio</title>
        {% endblock title_head %}
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'inicio:inicio' %}">Inicio</a>
                <a class="navbar-brand" href="{% url 'inicio:crear-persona' %}">Crear Persona</a>
                {% comment %} <a class="navbar-brand" href="{% url 'inicio:crear-pajaro' %}">Crear Pajaro</a> {% endcomment %}
                <a class="navbar-brand" href="{% url 'inicio:crear-gato' %}">Crear Gato</a>
                <a class="btn btn-primary" href="#signup">Iniciar</a>
            </div>
        </nav>

        {% block contenido %}
    <!-- Masthead-->
            <header class="masthead">
             <div class="container position-relative">
                 <div class="row justify-content-center">
                   <div class="col-xl-6">
                           <div class="text-center text-white">
                          <!-- Page heading-->
                         <h1 class="mb-5">Pre-entrega final </h1>
                     </div>
                   </div>
                 </div>
            </header>
            </div>
        {% endblock contenido  %}

        {% block formulario  %}
    
        {% endblock formulario  %}


        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><a href="#!">About</a></li>
                            <li class="list-inline-item">⋅</li>
                            <li class="list-inline-item"><a href="#!">Contact</a></li>
                            <li class="list-inline-item"></li>
                            <li class="list-inline-item"><a href="#!"></a></li>
                            <li class="list-inline-item"></li>
                            <li class="list-inline-item"><a href="#!"></a></li>
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2023. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
   

</html>

templates/crear-gato.html
{% extends 'base.html' %}

{% block  title_head %}
        <title>Crear Gato</title>
{% endblock title_head %}

{% block contenido  %}

    <header class="masthead">
      <div class="container position-relative">
         <div class="row justify-content-center">
           <div class="col-xl-6">
                   <div class="text-center text-white">
                   <!-- Page heading-->
                   <h1 class="mb-5">Crear </h1>
              </div>
            </div>
           </div>
       </div>
    </header>

{% endblock contenido  %}





{% block formulario %}
{% if gato  %}
<h2>Se creo al gato  {{gato.nombre}} y tiene {{gato.edad}} años </h2>
{% endif %}
<form action="" method="POST">
    {% csrf_token %}
   <table>
    {{formulariogato}}    
   </table>
    <button>Crear</button>
</form>
{% endblock formulario %}

templates/crear-persona.html
{% extends 'base.html' %}

{% block  title_head %}
        <title>Crear Persona</title>
{% endblock title_head %}

{% block contenido  %}

    <header class="masthead">
      <div class="container position-relative">
         <div class="row justify-content-center">
           <div class="col-xl-6">
                   <div class="text-center text-white">
                   <!-- Page heading-->
                   <h1 class="mb-5">Crear </h1>
              </div>
            </div>
           </div>
       </div>
    </header>

{% endblock contenido  %}





{% block persona %}
{% if persona  %}
<h2>Se creo a {{persona.nombre}} y tiene {{persona.edad}} años </h2>
{% endif %}
<form action="" method="POST">
    {% csrf_token %}
 
    {{formulario}}
    <button>Crear</button>

    
</form>
{% endblock persona %}





templates/inicio.html
{% extends 'base.html' %}

{% block contenido %}
<!-- Masthead-->
<header class="masthead">
    <div class="container position-relative">
        <div class="row justify-content-center">
             <div class="col-xl-6">
                <div class="text-center text-white">
                         <!-- Page heading-->
                     <h1 class="mb-5">3ra Pre-entrega</h1>
                </div>
             </div>
        </div>
     </div>
</header>
{% endblock contenido %}

templates/prueba.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content=>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hola<h1> 
    <p>{{mensaje}}<p>
            
</body>
</html>    